#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xfce4-panel &
xset r rate 300 50 &
nitrogen --restore &
compton -c &
dunst &
xfce4-power-manager &
numlockx on &

M(){
        xrandr --output eDP-1 --mode 1366x768 --pos 0x0 --rotate normal --output HDMI-1 --primary --mode 1360x768 --pos 1366x0 --rotate normal --output DP-1 --off
        bspc config -m HDMI-1 top_padding 35
        bspc config -m eDP-1 top_padding 0
        bspc monitor eDP-1 -d 1
        bspc monitor HDMI-1 -d 2
}

D(){
        moniteur
        bspc config top_padding 35
        bspc monitor -d 1
}

a="$(xrandr | grep -o "disconnected" | wc -l)"
case $a in
        "1") $(M);;
        "2") $(D);;
esac

bspc config border_width         1
bspc config window_gap           7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#BABDB6"
bspc config presel_feedback_color "#6272a4"
