#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
xfce4-panel &
xset r rate 300 50 &
nitrogen --restore &
picom -c &
dunst &
xfce4-power-manager &
numlockx on &
setwall &


bspc monitor -d 1 2 3 4

bspc config border_width         1
bspc config window_gap           7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#BABDB6"
bspc config presel_feedback_color "#6272a4"
